/**                                                                     
 *  /file guwhiteboardtypelist_c_typestrings_generated.c                
 *                                                                      
 *  Created by Carl Lusty in 2013.                                      
 *  Copyright (c) 2013 Carl Lusty                                       
 *  All rights reserved.                                                
 */                                                                     

#include "gusimplewhiteboard.h"
#include "guwhiteboardtypelist_c_generated.h"

//Generated on: Mon Jul 28 18:08:36 2014
//Generated by user: carl

const char *WBTypes_stringValues[] = 
{
        "*",
        "Print",
        "Say",
        "Speech",
        "QSay",
        "QSpeech",
        "SpeechOutput",
        "GCGameState",
        "WALK_Command",
        "WALK_Status",
        "MOTION_Commands",
        "MOTION_Status",
        "HAL_HeadTarget",
        "SENSORS_FootSensors",
        "SENSORS_BodySensors",
        "SENSORS_LedsSensors",
        "SENSORS_LegJointTemps",
        "SENSORS_TorsoJointTemps",
        "SENSORS_LegJointSensors",
        "SENSORS_TorsoJointSensors",
        "SENSORS_SonarSensors",
        "fsm_control",
        "fsm_status",
        "fsm_names",
        "example_type",
        "FilteredGoalSighting",
        "NAO_State",
        "UDPReceiverNotification",
        "PlayerNumber",
        "PlayerNumber",
        "guvision_control",
        "guvision_status",
        "FFTStatus",
        "FSOsighting",
        "TopParticles",
        "FilteredBallSighting",
        "PF_ControlStatus_Modes",
        "WEBOTS_NXT_bridge",
        "WEBOTS_NXT_encoders",
        "WEBOTS_NXT_camera",
        "WEBOTS_NXT_walk_isRunning",
        "WEBOTS_NXT_deadReakoning_walk",
        "WEBOTS_NXT_colorLine_walk",
        "WEBOTS_NXT_gridMotions",
        "VisionBall",
        "VisionGoals",
        "WalkData",
        "TeleoperationControlStatus",
        "TeleoperationConnection",
        "UDPWBNumber",
        "WEBOTS_NXT_bumper",
        "WEBOTS_NXT_vector_bridge",
        "VisionLines"
};      

