/**                                                                     
 *  /file WBFunctor_types_generated.h                                   
 *                                                                      
 *  Created by Carl Lusty in 2013.                                      
 *  Copyright (c) 2013 Carl Lusty                                       
 *  All rights reserved.                                                
 */                                                                     

#pragma clang diagnostic push                                           
#pragma clang diagnostic ignored "-Wpadded"                           
#pragma clang diagnostic ignored "-Wold-style-cast"                   

//Generated on: Mon Jul 28 18:08:36 2014
//Generated by user: carl

template <typename Print_WBFunctor_T >
class Print_WBFunctor: public WBFunctor<Print_WBFunctor_T > 
{
public:
        Print_WBFunctor(Print_WBFunctor_T* obj, void (Print_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t): WBFunctor<Print_WBFunctor_T >(obj, (void (Print_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                std::string result = guWhiteboard::Print_t().get_from(m);
                Print_function_t funct((void (Print_WBFunctor_T::*)(guWhiteboard::WBTypes, std::string &))WBFunctor<Print_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<Print_WBFunctor_T >::fObject->*funct)(WBFunctor<Print_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (Print_WBFunctor_T::*Print_function_t) (guWhiteboard::WBTypes, std::string &);

        static WBFunctorBase *bind(Print_WBFunctor_T *obj, void (Print_WBFunctor_T::*f)(guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t) { return new Print_WBFunctor<Print_WBFunctor_T >(obj, f, t); }
};



template <typename Say_WBFunctor_T >
class Say_WBFunctor: public WBFunctor<Say_WBFunctor_T > 
{
public:
        Say_WBFunctor(Say_WBFunctor_T* obj, void (Say_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t): WBFunctor<Say_WBFunctor_T >(obj, (void (Say_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                std::string result = guWhiteboard::Say_t().get_from(m);
                Say_function_t funct((void (Say_WBFunctor_T::*)(guWhiteboard::WBTypes, std::string &))WBFunctor<Say_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<Say_WBFunctor_T >::fObject->*funct)(WBFunctor<Say_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (Say_WBFunctor_T::*Say_function_t) (guWhiteboard::WBTypes, std::string &);

        static WBFunctorBase *bind(Say_WBFunctor_T *obj, void (Say_WBFunctor_T::*f)(guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t) { return new Say_WBFunctor<Say_WBFunctor_T >(obj, f, t); }
};



template <typename Speech_WBFunctor_T >
class Speech_WBFunctor: public WBFunctor<Speech_WBFunctor_T > 
{
public:
        Speech_WBFunctor(Speech_WBFunctor_T* obj, void (Speech_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t): WBFunctor<Speech_WBFunctor_T >(obj, (void (Speech_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                std::string result = guWhiteboard::Speech_t().get_from(m);
                Speech_function_t funct((void (Speech_WBFunctor_T::*)(guWhiteboard::WBTypes, std::string &))WBFunctor<Speech_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<Speech_WBFunctor_T >::fObject->*funct)(WBFunctor<Speech_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (Speech_WBFunctor_T::*Speech_function_t) (guWhiteboard::WBTypes, std::string &);

        static WBFunctorBase *bind(Speech_WBFunctor_T *obj, void (Speech_WBFunctor_T::*f)(guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t) { return new Speech_WBFunctor<Speech_WBFunctor_T >(obj, f, t); }
};



template <typename QSay_WBFunctor_T >
class QSay_WBFunctor: public WBFunctor<QSay_WBFunctor_T > 
{
public:
        QSay_WBFunctor(QSay_WBFunctor_T* obj, void (QSay_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t): WBFunctor<QSay_WBFunctor_T >(obj, (void (QSay_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                std::string result = guWhiteboard::QSay_t().get_from(m);
                QSay_function_t funct((void (QSay_WBFunctor_T::*)(guWhiteboard::WBTypes, std::string &))WBFunctor<QSay_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<QSay_WBFunctor_T >::fObject->*funct)(WBFunctor<QSay_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (QSay_WBFunctor_T::*QSay_function_t) (guWhiteboard::WBTypes, std::string &);

        static WBFunctorBase *bind(QSay_WBFunctor_T *obj, void (QSay_WBFunctor_T::*f)(guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t) { return new QSay_WBFunctor<QSay_WBFunctor_T >(obj, f, t); }
};



template <typename QSpeech_WBFunctor_T >
class QSpeech_WBFunctor: public WBFunctor<QSpeech_WBFunctor_T > 
{
public:
        QSpeech_WBFunctor(QSpeech_WBFunctor_T* obj, void (QSpeech_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t): WBFunctor<QSpeech_WBFunctor_T >(obj, (void (QSpeech_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                std::string result = guWhiteboard::QSpeech_t().get_from(m);
                QSpeech_function_t funct((void (QSpeech_WBFunctor_T::*)(guWhiteboard::WBTypes, std::string &))WBFunctor<QSpeech_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<QSpeech_WBFunctor_T >::fObject->*funct)(WBFunctor<QSpeech_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (QSpeech_WBFunctor_T::*QSpeech_function_t) (guWhiteboard::WBTypes, std::string &);

        static WBFunctorBase *bind(QSpeech_WBFunctor_T *obj, void (QSpeech_WBFunctor_T::*f)(guWhiteboard::WBTypes, std::string &), guWhiteboard::WBTypes t) { return new QSpeech_WBFunctor<QSpeech_WBFunctor_T >(obj, f, t); }
};



template <typename SpeechOutput_WBFunctor_T >
class SpeechOutput_WBFunctor: public WBFunctor<SpeechOutput_WBFunctor_T > 
{
public:
        SpeechOutput_WBFunctor(SpeechOutput_WBFunctor_T* obj, void (SpeechOutput_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, bool &), guWhiteboard::WBTypes t): WBFunctor<SpeechOutput_WBFunctor_T >(obj, (void (SpeechOutput_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                bool result = guWhiteboard::SpeechOutput_t().get_from(m);
                SpeechOutput_function_t funct((void (SpeechOutput_WBFunctor_T::*)(guWhiteboard::WBTypes, bool &))WBFunctor<SpeechOutput_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SpeechOutput_WBFunctor_T >::fObject->*funct)(WBFunctor<SpeechOutput_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SpeechOutput_WBFunctor_T::*SpeechOutput_function_t) (guWhiteboard::WBTypes, bool &);

        static WBFunctorBase *bind(SpeechOutput_WBFunctor_T *obj, void (SpeechOutput_WBFunctor_T::*f)(guWhiteboard::WBTypes, bool &), guWhiteboard::WBTypes t) { return new SpeechOutput_WBFunctor<SpeechOutput_WBFunctor_T >(obj, f, t); }
};



#ifdef GCGameState_DEFINED
template <typename GCGameState_WBFunctor_T >
class GCGameState_WBFunctor: public WBFunctor<GCGameState_WBFunctor_T > 
{
public:
        GCGameState_WBFunctor(GCGameState_WBFunctor_T* obj, void (GCGameState_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::GCGameState &), guWhiteboard::WBTypes t): WBFunctor<GCGameState_WBFunctor_T >(obj, (void (GCGameState_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::GCGameState result = guWhiteboard::GCGameState_t().get_from(m);
                GCGameState_function_t funct((void (GCGameState_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::GCGameState &))WBFunctor<GCGameState_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<GCGameState_WBFunctor_T >::fObject->*funct)(WBFunctor<GCGameState_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (GCGameState_WBFunctor_T::*GCGameState_function_t) (guWhiteboard::WBTypes, guWhiteboard::GCGameState &);

        static WBFunctorBase *bind(GCGameState_WBFunctor_T *obj, void (GCGameState_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::GCGameState &), guWhiteboard::WBTypes t) { return new GCGameState_WBFunctor<GCGameState_WBFunctor_T >(obj, f, t); }
};

#endif //GCGameState_DEFINED


#ifdef WALK_ControlStatus_DEFINED
template <typename WALK_Command_WBFunctor_T >
class WALK_Command_WBFunctor: public WBFunctor<WALK_Command_WBFunctor_T > 
{
public:
        WALK_Command_WBFunctor(WALK_Command_WBFunctor_T* obj, void (WALK_Command_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &), guWhiteboard::WBTypes t): WBFunctor<WALK_Command_WBFunctor_T >(obj, (void (WALK_Command_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WALK_ControlStatus result = guWhiteboard::WALK_Command_t().get_from(m);
                WALK_Command_function_t funct((void (WALK_Command_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &))WBFunctor<WALK_Command_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WALK_Command_WBFunctor_T >::fObject->*funct)(WBFunctor<WALK_Command_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WALK_Command_WBFunctor_T::*WALK_Command_function_t) (guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &);

        static WBFunctorBase *bind(WALK_Command_WBFunctor_T *obj, void (WALK_Command_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &), guWhiteboard::WBTypes t) { return new WALK_Command_WBFunctor<WALK_Command_WBFunctor_T >(obj, f, t); }
};

#endif //WALK_ControlStatus_DEFINED


#ifdef WALK_ControlStatus_DEFINED
template <typename WALK_Status_WBFunctor_T >
class WALK_Status_WBFunctor: public WBFunctor<WALK_Status_WBFunctor_T > 
{
public:
        WALK_Status_WBFunctor(WALK_Status_WBFunctor_T* obj, void (WALK_Status_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &), guWhiteboard::WBTypes t): WBFunctor<WALK_Status_WBFunctor_T >(obj, (void (WALK_Status_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WALK_ControlStatus result = guWhiteboard::WALK_Status_t().get_from(m);
                WALK_Status_function_t funct((void (WALK_Status_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &))WBFunctor<WALK_Status_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WALK_Status_WBFunctor_T >::fObject->*funct)(WBFunctor<WALK_Status_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WALK_Status_WBFunctor_T::*WALK_Status_function_t) (guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &);

        static WBFunctorBase *bind(WALK_Status_WBFunctor_T *obj, void (WALK_Status_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WALK_ControlStatus &), guWhiteboard::WBTypes t) { return new WALK_Status_WBFunctor<WALK_Status_WBFunctor_T >(obj, f, t); }
};

#endif //WALK_ControlStatus_DEFINED


#ifdef MOTION_Commands_DEFINED
template <typename MOTION_Commands_WBFunctor_T >
class MOTION_Commands_WBFunctor: public WBFunctor<MOTION_Commands_WBFunctor_T > 
{
public:
        MOTION_Commands_WBFunctor(MOTION_Commands_WBFunctor_T* obj, void (MOTION_Commands_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::MOTION_Commands &), guWhiteboard::WBTypes t): WBFunctor<MOTION_Commands_WBFunctor_T >(obj, (void (MOTION_Commands_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::MOTION_Commands result = guWhiteboard::MOTION_Commands_t().get_from(m);
                MOTION_Commands_function_t funct((void (MOTION_Commands_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::MOTION_Commands &))WBFunctor<MOTION_Commands_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<MOTION_Commands_WBFunctor_T >::fObject->*funct)(WBFunctor<MOTION_Commands_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (MOTION_Commands_WBFunctor_T::*MOTION_Commands_function_t) (guWhiteboard::WBTypes, guWhiteboard::MOTION_Commands &);

        static WBFunctorBase *bind(MOTION_Commands_WBFunctor_T *obj, void (MOTION_Commands_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::MOTION_Commands &), guWhiteboard::WBTypes t) { return new MOTION_Commands_WBFunctor<MOTION_Commands_WBFunctor_T >(obj, f, t); }
};

#endif //MOTION_Commands_DEFINED


#ifdef MOTION_Status_DEFINED
template <typename MOTION_Status_WBFunctor_T >
class MOTION_Status_WBFunctor: public WBFunctor<MOTION_Status_WBFunctor_T > 
{
public:
        MOTION_Status_WBFunctor(MOTION_Status_WBFunctor_T* obj, void (MOTION_Status_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::MOTION_Status &), guWhiteboard::WBTypes t): WBFunctor<MOTION_Status_WBFunctor_T >(obj, (void (MOTION_Status_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::MOTION_Status result = guWhiteboard::MOTION_Status_t().get_from(m);
                MOTION_Status_function_t funct((void (MOTION_Status_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::MOTION_Status &))WBFunctor<MOTION_Status_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<MOTION_Status_WBFunctor_T >::fObject->*funct)(WBFunctor<MOTION_Status_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (MOTION_Status_WBFunctor_T::*MOTION_Status_function_t) (guWhiteboard::WBTypes, guWhiteboard::MOTION_Status &);

        static WBFunctorBase *bind(MOTION_Status_WBFunctor_T *obj, void (MOTION_Status_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::MOTION_Status &), guWhiteboard::WBTypes t) { return new MOTION_Status_WBFunctor<MOTION_Status_WBFunctor_T >(obj, f, t); }
};

#endif //MOTION_Status_DEFINED


#ifdef HAL_HeadTarget_DEFINED
template <typename HAL_HeadTarget_WBFunctor_T >
class HAL_HeadTarget_WBFunctor: public WBFunctor<HAL_HeadTarget_WBFunctor_T > 
{
public:
        HAL_HeadTarget_WBFunctor(HAL_HeadTarget_WBFunctor_T* obj, void (HAL_HeadTarget_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::HAL_HeadTarget &), guWhiteboard::WBTypes t): WBFunctor<HAL_HeadTarget_WBFunctor_T >(obj, (void (HAL_HeadTarget_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::HAL_HeadTarget result = guWhiteboard::HAL_HeadTarget_t().get_from(m);
                HAL_HeadTarget_function_t funct((void (HAL_HeadTarget_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::HAL_HeadTarget &))WBFunctor<HAL_HeadTarget_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<HAL_HeadTarget_WBFunctor_T >::fObject->*funct)(WBFunctor<HAL_HeadTarget_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (HAL_HeadTarget_WBFunctor_T::*HAL_HeadTarget_function_t) (guWhiteboard::WBTypes, guWhiteboard::HAL_HeadTarget &);

        static WBFunctorBase *bind(HAL_HeadTarget_WBFunctor_T *obj, void (HAL_HeadTarget_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::HAL_HeadTarget &), guWhiteboard::WBTypes t) { return new HAL_HeadTarget_WBFunctor<HAL_HeadTarget_WBFunctor_T >(obj, f, t); }
};

#endif //HAL_HeadTarget_DEFINED


#ifdef SENSORS_FootSensors_DEFINED
template <typename SENSORS_FootSensors_WBFunctor_T >
class SENSORS_FootSensors_WBFunctor: public WBFunctor<SENSORS_FootSensors_WBFunctor_T > 
{
public:
        SENSORS_FootSensors_WBFunctor(SENSORS_FootSensors_WBFunctor_T* obj, void (SENSORS_FootSensors_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_FootSensors &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_FootSensors_WBFunctor_T >(obj, (void (SENSORS_FootSensors_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_FootSensors result = guWhiteboard::SENSORS_FootSensors_t().get_from(m);
                SENSORS_FootSensors_function_t funct((void (SENSORS_FootSensors_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_FootSensors &))WBFunctor<SENSORS_FootSensors_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_FootSensors_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_FootSensors_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_FootSensors_WBFunctor_T::*SENSORS_FootSensors_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_FootSensors &);

        static WBFunctorBase *bind(SENSORS_FootSensors_WBFunctor_T *obj, void (SENSORS_FootSensors_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_FootSensors &), guWhiteboard::WBTypes t) { return new SENSORS_FootSensors_WBFunctor<SENSORS_FootSensors_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_FootSensors_DEFINED


#ifdef SENSORS_BodySensors_DEFINED
template <typename SENSORS_BodySensors_WBFunctor_T >
class SENSORS_BodySensors_WBFunctor: public WBFunctor<SENSORS_BodySensors_WBFunctor_T > 
{
public:
        SENSORS_BodySensors_WBFunctor(SENSORS_BodySensors_WBFunctor_T* obj, void (SENSORS_BodySensors_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_BodySensors &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_BodySensors_WBFunctor_T >(obj, (void (SENSORS_BodySensors_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_BodySensors result = guWhiteboard::SENSORS_BodySensors_t().get_from(m);
                SENSORS_BodySensors_function_t funct((void (SENSORS_BodySensors_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_BodySensors &))WBFunctor<SENSORS_BodySensors_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_BodySensors_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_BodySensors_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_BodySensors_WBFunctor_T::*SENSORS_BodySensors_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_BodySensors &);

        static WBFunctorBase *bind(SENSORS_BodySensors_WBFunctor_T *obj, void (SENSORS_BodySensors_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_BodySensors &), guWhiteboard::WBTypes t) { return new SENSORS_BodySensors_WBFunctor<SENSORS_BodySensors_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_BodySensors_DEFINED


#ifdef SENSORS_LedsSensors_DEFINED
template <typename SENSORS_LedsSensors_WBFunctor_T >
class SENSORS_LedsSensors_WBFunctor: public WBFunctor<SENSORS_LedsSensors_WBFunctor_T > 
{
public:
        SENSORS_LedsSensors_WBFunctor(SENSORS_LedsSensors_WBFunctor_T* obj, void (SENSORS_LedsSensors_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_LedsSensors &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_LedsSensors_WBFunctor_T >(obj, (void (SENSORS_LedsSensors_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_LedsSensors result = guWhiteboard::SENSORS_LedsSensors_t().get_from(m);
                SENSORS_LedsSensors_function_t funct((void (SENSORS_LedsSensors_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_LedsSensors &))WBFunctor<SENSORS_LedsSensors_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_LedsSensors_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_LedsSensors_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_LedsSensors_WBFunctor_T::*SENSORS_LedsSensors_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_LedsSensors &);

        static WBFunctorBase *bind(SENSORS_LedsSensors_WBFunctor_T *obj, void (SENSORS_LedsSensors_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_LedsSensors &), guWhiteboard::WBTypes t) { return new SENSORS_LedsSensors_WBFunctor<SENSORS_LedsSensors_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_LedsSensors_DEFINED


#ifdef SENSORS_LegJointTemps_DEFINED
template <typename SENSORS_LegJointTemps_WBFunctor_T >
class SENSORS_LegJointTemps_WBFunctor: public WBFunctor<SENSORS_LegJointTemps_WBFunctor_T > 
{
public:
        SENSORS_LegJointTemps_WBFunctor(SENSORS_LegJointTemps_WBFunctor_T* obj, void (SENSORS_LegJointTemps_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointTemps &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_LegJointTemps_WBFunctor_T >(obj, (void (SENSORS_LegJointTemps_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_LegJointTemps result = guWhiteboard::SENSORS_LegJointTemps_t().get_from(m);
                SENSORS_LegJointTemps_function_t funct((void (SENSORS_LegJointTemps_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointTemps &))WBFunctor<SENSORS_LegJointTemps_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_LegJointTemps_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_LegJointTemps_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_LegJointTemps_WBFunctor_T::*SENSORS_LegJointTemps_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointTemps &);

        static WBFunctorBase *bind(SENSORS_LegJointTemps_WBFunctor_T *obj, void (SENSORS_LegJointTemps_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointTemps &), guWhiteboard::WBTypes t) { return new SENSORS_LegJointTemps_WBFunctor<SENSORS_LegJointTemps_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_LegJointTemps_DEFINED


#ifdef SENSORS_TorsoJointTemps_DEFINED
template <typename SENSORS_TorsoJointTemps_WBFunctor_T >
class SENSORS_TorsoJointTemps_WBFunctor: public WBFunctor<SENSORS_TorsoJointTemps_WBFunctor_T > 
{
public:
        SENSORS_TorsoJointTemps_WBFunctor(SENSORS_TorsoJointTemps_WBFunctor_T* obj, void (SENSORS_TorsoJointTemps_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointTemps &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_TorsoJointTemps_WBFunctor_T >(obj, (void (SENSORS_TorsoJointTemps_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_TorsoJointTemps result = guWhiteboard::SENSORS_TorsoJointTemps_t().get_from(m);
                SENSORS_TorsoJointTemps_function_t funct((void (SENSORS_TorsoJointTemps_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointTemps &))WBFunctor<SENSORS_TorsoJointTemps_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_TorsoJointTemps_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_TorsoJointTemps_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_TorsoJointTemps_WBFunctor_T::*SENSORS_TorsoJointTemps_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointTemps &);

        static WBFunctorBase *bind(SENSORS_TorsoJointTemps_WBFunctor_T *obj, void (SENSORS_TorsoJointTemps_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointTemps &), guWhiteboard::WBTypes t) { return new SENSORS_TorsoJointTemps_WBFunctor<SENSORS_TorsoJointTemps_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_TorsoJointTemps_DEFINED


#ifdef SENSORS_LegJointSensors_DEFINED
template <typename SENSORS_LegJointSensors_WBFunctor_T >
class SENSORS_LegJointSensors_WBFunctor: public WBFunctor<SENSORS_LegJointSensors_WBFunctor_T > 
{
public:
        SENSORS_LegJointSensors_WBFunctor(SENSORS_LegJointSensors_WBFunctor_T* obj, void (SENSORS_LegJointSensors_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointSensors &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_LegJointSensors_WBFunctor_T >(obj, (void (SENSORS_LegJointSensors_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_LegJointSensors result = guWhiteboard::SENSORS_LegJointSensors_t().get_from(m);
                SENSORS_LegJointSensors_function_t funct((void (SENSORS_LegJointSensors_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointSensors &))WBFunctor<SENSORS_LegJointSensors_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_LegJointSensors_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_LegJointSensors_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_LegJointSensors_WBFunctor_T::*SENSORS_LegJointSensors_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointSensors &);

        static WBFunctorBase *bind(SENSORS_LegJointSensors_WBFunctor_T *obj, void (SENSORS_LegJointSensors_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_LegJointSensors &), guWhiteboard::WBTypes t) { return new SENSORS_LegJointSensors_WBFunctor<SENSORS_LegJointSensors_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_LegJointSensors_DEFINED


#ifdef SENSORS_TorsoJointSensors_DEFINED
template <typename SENSORS_TorsoJointSensors_WBFunctor_T >
class SENSORS_TorsoJointSensors_WBFunctor: public WBFunctor<SENSORS_TorsoJointSensors_WBFunctor_T > 
{
public:
        SENSORS_TorsoJointSensors_WBFunctor(SENSORS_TorsoJointSensors_WBFunctor_T* obj, void (SENSORS_TorsoJointSensors_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointSensors &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_TorsoJointSensors_WBFunctor_T >(obj, (void (SENSORS_TorsoJointSensors_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_TorsoJointSensors result = guWhiteboard::SENSORS_TorsoJointSensors_t().get_from(m);
                SENSORS_TorsoJointSensors_function_t funct((void (SENSORS_TorsoJointSensors_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointSensors &))WBFunctor<SENSORS_TorsoJointSensors_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_TorsoJointSensors_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_TorsoJointSensors_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_TorsoJointSensors_WBFunctor_T::*SENSORS_TorsoJointSensors_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointSensors &);

        static WBFunctorBase *bind(SENSORS_TorsoJointSensors_WBFunctor_T *obj, void (SENSORS_TorsoJointSensors_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_TorsoJointSensors &), guWhiteboard::WBTypes t) { return new SENSORS_TorsoJointSensors_WBFunctor<SENSORS_TorsoJointSensors_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_TorsoJointSensors_DEFINED


#ifdef SENSORS_SonarSensors_DEFINED
template <typename SENSORS_SonarSensors_WBFunctor_T >
class SENSORS_SonarSensors_WBFunctor: public WBFunctor<SENSORS_SonarSensors_WBFunctor_T > 
{
public:
        SENSORS_SonarSensors_WBFunctor(SENSORS_SonarSensors_WBFunctor_T* obj, void (SENSORS_SonarSensors_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_SonarSensors &), guWhiteboard::WBTypes t): WBFunctor<SENSORS_SonarSensors_WBFunctor_T >(obj, (void (SENSORS_SonarSensors_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::SENSORS_SonarSensors result = guWhiteboard::SENSORS_SonarSensors_t().get_from(m);
                SENSORS_SonarSensors_function_t funct((void (SENSORS_SonarSensors_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_SonarSensors &))WBFunctor<SENSORS_SonarSensors_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<SENSORS_SonarSensors_WBFunctor_T >::fObject->*funct)(WBFunctor<SENSORS_SonarSensors_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (SENSORS_SonarSensors_WBFunctor_T::*SENSORS_SonarSensors_function_t) (guWhiteboard::WBTypes, guWhiteboard::SENSORS_SonarSensors &);

        static WBFunctorBase *bind(SENSORS_SonarSensors_WBFunctor_T *obj, void (SENSORS_SonarSensors_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::SENSORS_SonarSensors &), guWhiteboard::WBTypes t) { return new SENSORS_SonarSensors_WBFunctor<SENSORS_SonarSensors_WBFunctor_T >(obj, f, t); }
};

#endif //SENSORS_SonarSensors_DEFINED


#ifdef FSMControlStatus_DEFINED
template <typename FSM_Control_WBFunctor_T >
class FSM_Control_WBFunctor: public WBFunctor<FSM_Control_WBFunctor_T > 
{
public:
        FSM_Control_WBFunctor(FSM_Control_WBFunctor_T* obj, void (FSM_Control_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &), guWhiteboard::WBTypes t): WBFunctor<FSM_Control_WBFunctor_T >(obj, (void (FSM_Control_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FSMControlStatus result = guWhiteboard::FSM_Control_t().get_from(m);
                FSM_Control_function_t funct((void (FSM_Control_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &))WBFunctor<FSM_Control_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FSM_Control_WBFunctor_T >::fObject->*funct)(WBFunctor<FSM_Control_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FSM_Control_WBFunctor_T::*FSM_Control_function_t) (guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &);

        static WBFunctorBase *bind(FSM_Control_WBFunctor_T *obj, void (FSM_Control_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &), guWhiteboard::WBTypes t) { return new FSM_Control_WBFunctor<FSM_Control_WBFunctor_T >(obj, f, t); }
};

#endif //FSMControlStatus_DEFINED


#ifdef FSMControlStatus_DEFINED
template <typename FSM_Status_WBFunctor_T >
class FSM_Status_WBFunctor: public WBFunctor<FSM_Status_WBFunctor_T > 
{
public:
        FSM_Status_WBFunctor(FSM_Status_WBFunctor_T* obj, void (FSM_Status_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &), guWhiteboard::WBTypes t): WBFunctor<FSM_Status_WBFunctor_T >(obj, (void (FSM_Status_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FSMControlStatus result = guWhiteboard::FSM_Status_t().get_from(m);
                FSM_Status_function_t funct((void (FSM_Status_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &))WBFunctor<FSM_Status_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FSM_Status_WBFunctor_T >::fObject->*funct)(WBFunctor<FSM_Status_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FSM_Status_WBFunctor_T::*FSM_Status_function_t) (guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &);

        static WBFunctorBase *bind(FSM_Status_WBFunctor_T *obj, void (FSM_Status_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FSMControlStatus &), guWhiteboard::WBTypes t) { return new FSM_Status_WBFunctor<FSM_Status_WBFunctor_T >(obj, f, t); }
};

#endif //FSMControlStatus_DEFINED


#ifdef FSMNames_DEFINED
template <typename FSM_Names_WBFunctor_T >
class FSM_Names_WBFunctor: public WBFunctor<FSM_Names_WBFunctor_T > 
{
public:
        FSM_Names_WBFunctor(FSM_Names_WBFunctor_T* obj, void (FSM_Names_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FSMNames &), guWhiteboard::WBTypes t): WBFunctor<FSM_Names_WBFunctor_T >(obj, (void (FSM_Names_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FSMNames result = guWhiteboard::FSM_Names_t().get_from(m);
                FSM_Names_function_t funct((void (FSM_Names_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FSMNames &))WBFunctor<FSM_Names_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FSM_Names_WBFunctor_T >::fObject->*funct)(WBFunctor<FSM_Names_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FSM_Names_WBFunctor_T::*FSM_Names_function_t) (guWhiteboard::WBTypes, guWhiteboard::FSMNames &);

        static WBFunctorBase *bind(FSM_Names_WBFunctor_T *obj, void (FSM_Names_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FSMNames &), guWhiteboard::WBTypes t) { return new FSM_Names_WBFunctor<FSM_Names_WBFunctor_T >(obj, f, t); }
};

#endif //FSMNames_DEFINED


#ifdef FilteredArrayOneDimObjects_DEFINED
template <typename FilteredGoalSighting_WBFunctor_T >
class FilteredGoalSighting_WBFunctor: public WBFunctor<FilteredGoalSighting_WBFunctor_T > 
{
public:
        FilteredGoalSighting_WBFunctor(FilteredGoalSighting_WBFunctor_T* obj, void (FilteredGoalSighting_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimObjects &), guWhiteboard::WBTypes t): WBFunctor<FilteredGoalSighting_WBFunctor_T >(obj, (void (FilteredGoalSighting_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FilteredArrayOneDimObjects result = guWhiteboard::FilteredGoalSighting_t().get_from(m);
                FilteredGoalSighting_function_t funct((void (FilteredGoalSighting_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimObjects &))WBFunctor<FilteredGoalSighting_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FilteredGoalSighting_WBFunctor_T >::fObject->*funct)(WBFunctor<FilteredGoalSighting_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FilteredGoalSighting_WBFunctor_T::*FilteredGoalSighting_function_t) (guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimObjects &);

        static WBFunctorBase *bind(FilteredGoalSighting_WBFunctor_T *obj, void (FilteredGoalSighting_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimObjects &), guWhiteboard::WBTypes t) { return new FilteredGoalSighting_WBFunctor<FilteredGoalSighting_WBFunctor_T >(obj, f, t); }
};

#endif //FilteredArrayOneDimObjects_DEFINED


#ifdef NAO_State_DEFINED
template <typename NAO_State_WBFunctor_T >
class NAO_State_WBFunctor: public WBFunctor<NAO_State_WBFunctor_T > 
{
public:
        NAO_State_WBFunctor(NAO_State_WBFunctor_T* obj, void (NAO_State_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::NAO_State &), guWhiteboard::WBTypes t): WBFunctor<NAO_State_WBFunctor_T >(obj, (void (NAO_State_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::NAO_State result = guWhiteboard::NAO_State_t().get_from(m);
                NAO_State_function_t funct((void (NAO_State_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::NAO_State &))WBFunctor<NAO_State_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<NAO_State_WBFunctor_T >::fObject->*funct)(WBFunctor<NAO_State_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (NAO_State_WBFunctor_T::*NAO_State_function_t) (guWhiteboard::WBTypes, guWhiteboard::NAO_State &);

        static WBFunctorBase *bind(NAO_State_WBFunctor_T *obj, void (NAO_State_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::NAO_State &), guWhiteboard::WBTypes t) { return new NAO_State_WBFunctor<NAO_State_WBFunctor_T >(obj, f, t); }
};

#endif //NAO_State_DEFINED


#ifdef GCGameState_DEFINED
template <typename UDPRN_WBFunctor_T >
class UDPRN_WBFunctor: public WBFunctor<UDPRN_WBFunctor_T > 
{
public:
        UDPRN_WBFunctor(UDPRN_WBFunctor_T* obj, void (UDPRN_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::GCGameState &), guWhiteboard::WBTypes t): WBFunctor<UDPRN_WBFunctor_T >(obj, (void (UDPRN_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::GCGameState result = guWhiteboard::UDPRN_t().get_from(m);
                UDPRN_function_t funct((void (UDPRN_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::GCGameState &))WBFunctor<UDPRN_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<UDPRN_WBFunctor_T >::fObject->*funct)(WBFunctor<UDPRN_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (UDPRN_WBFunctor_T::*UDPRN_function_t) (guWhiteboard::WBTypes, guWhiteboard::GCGameState &);

        static WBFunctorBase *bind(UDPRN_WBFunctor_T *obj, void (UDPRN_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::GCGameState &), guWhiteboard::WBTypes t) { return new UDPRN_WBFunctor<UDPRN_WBFunctor_T >(obj, f, t); }
};

#endif //GCGameState_DEFINED


template <typename PlayerNumber_WBFunctor_T >
class PlayerNumber_WBFunctor: public WBFunctor<PlayerNumber_WBFunctor_T > 
{
public:
        PlayerNumber_WBFunctor(PlayerNumber_WBFunctor_T* obj, void (PlayerNumber_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t): WBFunctor<PlayerNumber_WBFunctor_T >(obj, (void (PlayerNumber_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                int result = guWhiteboard::PlayerNumber_t().get_from(m);
                PlayerNumber_function_t funct((void (PlayerNumber_WBFunctor_T::*)(guWhiteboard::WBTypes, int &))WBFunctor<PlayerNumber_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<PlayerNumber_WBFunctor_T >::fObject->*funct)(WBFunctor<PlayerNumber_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (PlayerNumber_WBFunctor_T::*PlayerNumber_function_t) (guWhiteboard::WBTypes, int &);

        static WBFunctorBase *bind(PlayerNumber_WBFunctor_T *obj, void (PlayerNumber_WBFunctor_T::*f)(guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t) { return new PlayerNumber_WBFunctor<PlayerNumber_WBFunctor_T >(obj, f, t); }
};



template <typename ManuallyPenalized_WBFunctor_T >
class ManuallyPenalized_WBFunctor: public WBFunctor<ManuallyPenalized_WBFunctor_T > 
{
public:
        ManuallyPenalized_WBFunctor(ManuallyPenalized_WBFunctor_T* obj, void (ManuallyPenalized_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t): WBFunctor<ManuallyPenalized_WBFunctor_T >(obj, (void (ManuallyPenalized_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                int result = guWhiteboard::ManuallyPenalized_t().get_from(m);
                ManuallyPenalized_function_t funct((void (ManuallyPenalized_WBFunctor_T::*)(guWhiteboard::WBTypes, int &))WBFunctor<ManuallyPenalized_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<ManuallyPenalized_WBFunctor_T >::fObject->*funct)(WBFunctor<ManuallyPenalized_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (ManuallyPenalized_WBFunctor_T::*ManuallyPenalized_function_t) (guWhiteboard::WBTypes, int &);

        static WBFunctorBase *bind(ManuallyPenalized_WBFunctor_T *obj, void (ManuallyPenalized_WBFunctor_T::*f)(guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t) { return new ManuallyPenalized_WBFunctor<ManuallyPenalized_WBFunctor_T >(obj, f, t); }
};



#ifdef VisionControlStatus_DEFINED
template <typename Vision_Control_WBFunctor_T >
class Vision_Control_WBFunctor: public WBFunctor<Vision_Control_WBFunctor_T > 
{
public:
        Vision_Control_WBFunctor(Vision_Control_WBFunctor_T* obj, void (Vision_Control_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &), guWhiteboard::WBTypes t): WBFunctor<Vision_Control_WBFunctor_T >(obj, (void (Vision_Control_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::VisionControlStatus result = guWhiteboard::Vision_Control_t().get_from(m);
                Vision_Control_function_t funct((void (Vision_Control_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &))WBFunctor<Vision_Control_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<Vision_Control_WBFunctor_T >::fObject->*funct)(WBFunctor<Vision_Control_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (Vision_Control_WBFunctor_T::*Vision_Control_function_t) (guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &);

        static WBFunctorBase *bind(Vision_Control_WBFunctor_T *obj, void (Vision_Control_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &), guWhiteboard::WBTypes t) { return new Vision_Control_WBFunctor<Vision_Control_WBFunctor_T >(obj, f, t); }
};

#endif //VisionControlStatus_DEFINED


#ifdef VisionControlStatus_DEFINED
template <typename Vision_Status_WBFunctor_T >
class Vision_Status_WBFunctor: public WBFunctor<Vision_Status_WBFunctor_T > 
{
public:
        Vision_Status_WBFunctor(Vision_Status_WBFunctor_T* obj, void (Vision_Status_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &), guWhiteboard::WBTypes t): WBFunctor<Vision_Status_WBFunctor_T >(obj, (void (Vision_Status_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::VisionControlStatus result = guWhiteboard::Vision_Status_t().get_from(m);
                Vision_Status_function_t funct((void (Vision_Status_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &))WBFunctor<Vision_Status_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<Vision_Status_WBFunctor_T >::fObject->*funct)(WBFunctor<Vision_Status_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (Vision_Status_WBFunctor_T::*Vision_Status_function_t) (guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &);

        static WBFunctorBase *bind(Vision_Status_WBFunctor_T *obj, void (Vision_Status_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::VisionControlStatus &), guWhiteboard::WBTypes t) { return new Vision_Status_WBFunctor<Vision_Status_WBFunctor_T >(obj, f, t); }
};

#endif //VisionControlStatus_DEFINED


#ifdef FFTStatus_DEFINED
template <typename FFTStatus_WBFunctor_T >
class FFTStatus_WBFunctor: public WBFunctor<FFTStatus_WBFunctor_T > 
{
public:
        FFTStatus_WBFunctor(FFTStatus_WBFunctor_T* obj, void (FFTStatus_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FFTStatus &), guWhiteboard::WBTypes t): WBFunctor<FFTStatus_WBFunctor_T >(obj, (void (FFTStatus_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FFTStatus result = guWhiteboard::FFTStatus_t().get_from(m);
                FFTStatus_function_t funct((void (FFTStatus_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FFTStatus &))WBFunctor<FFTStatus_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FFTStatus_WBFunctor_T >::fObject->*funct)(WBFunctor<FFTStatus_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FFTStatus_WBFunctor_T::*FFTStatus_function_t) (guWhiteboard::WBTypes, guWhiteboard::FFTStatus &);

        static WBFunctorBase *bind(FFTStatus_WBFunctor_T *obj, void (FFTStatus_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FFTStatus &), guWhiteboard::WBTypes t) { return new FFTStatus_WBFunctor<FFTStatus_WBFunctor_T >(obj, f, t); }
};

#endif //FFTStatus_DEFINED


#ifdef FilteredArrayOneDimSonar_DEFINED
template <typename FSOsighting_WBFunctor_T >
class FSOsighting_WBFunctor: public WBFunctor<FSOsighting_WBFunctor_T > 
{
public:
        FSOsighting_WBFunctor(FSOsighting_WBFunctor_T* obj, void (FSOsighting_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimSonar &), guWhiteboard::WBTypes t): WBFunctor<FSOsighting_WBFunctor_T >(obj, (void (FSOsighting_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FilteredArrayOneDimSonar result = guWhiteboard::FSOsighting_t().get_from(m);
                FSOsighting_function_t funct((void (FSOsighting_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimSonar &))WBFunctor<FSOsighting_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FSOsighting_WBFunctor_T >::fObject->*funct)(WBFunctor<FSOsighting_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FSOsighting_WBFunctor_T::*FSOsighting_function_t) (guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimSonar &);

        static WBFunctorBase *bind(FSOsighting_WBFunctor_T *obj, void (FSOsighting_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimSonar &), guWhiteboard::WBTypes t) { return new FSOsighting_WBFunctor<FSOsighting_WBFunctor_T >(obj, f, t); }
};

#endif //FilteredArrayOneDimSonar_DEFINED


#ifdef TopParticles_DEFINED
template <typename TopParticles_WBFunctor_T >
class TopParticles_WBFunctor: public WBFunctor<TopParticles_WBFunctor_T > 
{
public:
        TopParticles_WBFunctor(TopParticles_WBFunctor_T* obj, void (TopParticles_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::TopParticles &), guWhiteboard::WBTypes t): WBFunctor<TopParticles_WBFunctor_T >(obj, (void (TopParticles_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::TopParticles result = guWhiteboard::TopParticles_t().get_from(m);
                TopParticles_function_t funct((void (TopParticles_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::TopParticles &))WBFunctor<TopParticles_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<TopParticles_WBFunctor_T >::fObject->*funct)(WBFunctor<TopParticles_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (TopParticles_WBFunctor_T::*TopParticles_function_t) (guWhiteboard::WBTypes, guWhiteboard::TopParticles &);

        static WBFunctorBase *bind(TopParticles_WBFunctor_T *obj, void (TopParticles_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::TopParticles &), guWhiteboard::WBTypes t) { return new TopParticles_WBFunctor<TopParticles_WBFunctor_T >(obj, f, t); }
};

#endif //TopParticles_DEFINED


#ifdef FilteredArrayOneDimBall_DEFINED
template <typename FilteredBallSighting_WBFunctor_T >
class FilteredBallSighting_WBFunctor: public WBFunctor<FilteredBallSighting_WBFunctor_T > 
{
public:
        FilteredBallSighting_WBFunctor(FilteredBallSighting_WBFunctor_T* obj, void (FilteredBallSighting_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimBall &), guWhiteboard::WBTypes t): WBFunctor<FilteredBallSighting_WBFunctor_T >(obj, (void (FilteredBallSighting_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::FilteredArrayOneDimBall result = guWhiteboard::FilteredBallSighting_t().get_from(m);
                FilteredBallSighting_function_t funct((void (FilteredBallSighting_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimBall &))WBFunctor<FilteredBallSighting_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<FilteredBallSighting_WBFunctor_T >::fObject->*funct)(WBFunctor<FilteredBallSighting_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (FilteredBallSighting_WBFunctor_T::*FilteredBallSighting_function_t) (guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimBall &);

        static WBFunctorBase *bind(FilteredBallSighting_WBFunctor_T *obj, void (FilteredBallSighting_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::FilteredArrayOneDimBall &), guWhiteboard::WBTypes t) { return new FilteredBallSighting_WBFunctor<FilteredBallSighting_WBFunctor_T >(obj, f, t); }
};

#endif //FilteredArrayOneDimBall_DEFINED


template <typename PF_ControlStatus_Modes_WBFunctor_T >
class PF_ControlStatus_Modes_WBFunctor: public WBFunctor<PF_ControlStatus_Modes_WBFunctor_T > 
{
public:
        PF_ControlStatus_Modes_WBFunctor(PF_ControlStatus_Modes_WBFunctor_T* obj, void (PF_ControlStatus_Modes_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t): WBFunctor<PF_ControlStatus_Modes_WBFunctor_T >(obj, (void (PF_ControlStatus_Modes_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                int result = guWhiteboard::PF_ControlStatus_Modes_t().get_from(m);
                PF_ControlStatus_Modes_function_t funct((void (PF_ControlStatus_Modes_WBFunctor_T::*)(guWhiteboard::WBTypes, int &))WBFunctor<PF_ControlStatus_Modes_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<PF_ControlStatus_Modes_WBFunctor_T >::fObject->*funct)(WBFunctor<PF_ControlStatus_Modes_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (PF_ControlStatus_Modes_WBFunctor_T::*PF_ControlStatus_Modes_function_t) (guWhiteboard::WBTypes, int &);

        static WBFunctorBase *bind(PF_ControlStatus_Modes_WBFunctor_T *obj, void (PF_ControlStatus_Modes_WBFunctor_T::*f)(guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t) { return new PF_ControlStatus_Modes_WBFunctor<PF_ControlStatus_Modes_WBFunctor_T >(obj, f, t); }
};



#ifdef WEBOTS_NXT_bridge_DEFINED
template <typename WEBOTS_NXT_bridge_WBFunctor_T >
class WEBOTS_NXT_bridge_WBFunctor: public WBFunctor<WEBOTS_NXT_bridge_WBFunctor_T > 
{
public:
        WEBOTS_NXT_bridge_WBFunctor(WEBOTS_NXT_bridge_WBFunctor_T* obj, void (WEBOTS_NXT_bridge_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bridge &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_bridge_WBFunctor_T >(obj, (void (WEBOTS_NXT_bridge_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_bridge result = guWhiteboard::WEBOTS_NXT_bridge_t().get_from(m);
                WEBOTS_NXT_bridge_function_t funct((void (WEBOTS_NXT_bridge_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bridge &))WBFunctor<WEBOTS_NXT_bridge_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_bridge_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_bridge_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_bridge_WBFunctor_T::*WEBOTS_NXT_bridge_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bridge &);

        static WBFunctorBase *bind(WEBOTS_NXT_bridge_WBFunctor_T *obj, void (WEBOTS_NXT_bridge_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bridge &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_bridge_WBFunctor<WEBOTS_NXT_bridge_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_bridge_DEFINED


#ifdef WEBOTS_NXT_encoders_DEFINED
template <typename WEBOTS_NXT_encoders_WBFunctor_T >
class WEBOTS_NXT_encoders_WBFunctor: public WBFunctor<WEBOTS_NXT_encoders_WBFunctor_T > 
{
public:
        WEBOTS_NXT_encoders_WBFunctor(WEBOTS_NXT_encoders_WBFunctor_T* obj, void (WEBOTS_NXT_encoders_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_encoders &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_encoders_WBFunctor_T >(obj, (void (WEBOTS_NXT_encoders_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_encoders result = guWhiteboard::WEBOTS_NXT_encoders_t().get_from(m);
                WEBOTS_NXT_encoders_function_t funct((void (WEBOTS_NXT_encoders_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_encoders &))WBFunctor<WEBOTS_NXT_encoders_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_encoders_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_encoders_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_encoders_WBFunctor_T::*WEBOTS_NXT_encoders_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_encoders &);

        static WBFunctorBase *bind(WEBOTS_NXT_encoders_WBFunctor_T *obj, void (WEBOTS_NXT_encoders_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_encoders &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_encoders_WBFunctor<WEBOTS_NXT_encoders_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_encoders_DEFINED


#ifdef WEBOTS_NXT_camera_DEFINED
template <typename WEBOTS_NXT_camera_WBFunctor_T >
class WEBOTS_NXT_camera_WBFunctor: public WBFunctor<WEBOTS_NXT_camera_WBFunctor_T > 
{
public:
        WEBOTS_NXT_camera_WBFunctor(WEBOTS_NXT_camera_WBFunctor_T* obj, void (WEBOTS_NXT_camera_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_camera &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_camera_WBFunctor_T >(obj, (void (WEBOTS_NXT_camera_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_camera result = guWhiteboard::WEBOTS_NXT_camera_t().get_from(m);
                WEBOTS_NXT_camera_function_t funct((void (WEBOTS_NXT_camera_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_camera &))WBFunctor<WEBOTS_NXT_camera_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_camera_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_camera_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_camera_WBFunctor_T::*WEBOTS_NXT_camera_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_camera &);

        static WBFunctorBase *bind(WEBOTS_NXT_camera_WBFunctor_T *obj, void (WEBOTS_NXT_camera_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_camera &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_camera_WBFunctor<WEBOTS_NXT_camera_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_camera_DEFINED


#ifdef WEBOTS_NXT_walk_isRunning_DEFINED
template <typename WEBOTS_NXT_walk_isRunning_WBFunctor_T >
class WEBOTS_NXT_walk_isRunning_WBFunctor: public WBFunctor<WEBOTS_NXT_walk_isRunning_WBFunctor_T > 
{
public:
        WEBOTS_NXT_walk_isRunning_WBFunctor(WEBOTS_NXT_walk_isRunning_WBFunctor_T* obj, void (WEBOTS_NXT_walk_isRunning_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_walk_isRunning &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_walk_isRunning_WBFunctor_T >(obj, (void (WEBOTS_NXT_walk_isRunning_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_walk_isRunning result = guWhiteboard::WEBOTS_NXT_walk_isRunning_t().get_from(m);
                WEBOTS_NXT_walk_isRunning_function_t funct((void (WEBOTS_NXT_walk_isRunning_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_walk_isRunning &))WBFunctor<WEBOTS_NXT_walk_isRunning_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_walk_isRunning_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_walk_isRunning_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_walk_isRunning_WBFunctor_T::*WEBOTS_NXT_walk_isRunning_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_walk_isRunning &);

        static WBFunctorBase *bind(WEBOTS_NXT_walk_isRunning_WBFunctor_T *obj, void (WEBOTS_NXT_walk_isRunning_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_walk_isRunning &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_walk_isRunning_WBFunctor<WEBOTS_NXT_walk_isRunning_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_walk_isRunning_DEFINED


#ifdef WEBOTS_NXT_deadReakoning_walk_DEFINED
template <typename WEBOTS_NXT_deadReakoning_walk_WBFunctor_T >
class WEBOTS_NXT_deadReakoning_walk_WBFunctor: public WBFunctor<WEBOTS_NXT_deadReakoning_walk_WBFunctor_T > 
{
public:
        WEBOTS_NXT_deadReakoning_walk_WBFunctor(WEBOTS_NXT_deadReakoning_walk_WBFunctor_T* obj, void (WEBOTS_NXT_deadReakoning_walk_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_deadReakoning_walk &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_deadReakoning_walk_WBFunctor_T >(obj, (void (WEBOTS_NXT_deadReakoning_walk_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_deadReakoning_walk result = guWhiteboard::WEBOTS_NXT_deadReakoning_walk_t().get_from(m);
                WEBOTS_NXT_deadReakoning_walk_function_t funct((void (WEBOTS_NXT_deadReakoning_walk_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_deadReakoning_walk &))WBFunctor<WEBOTS_NXT_deadReakoning_walk_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_deadReakoning_walk_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_deadReakoning_walk_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_deadReakoning_walk_WBFunctor_T::*WEBOTS_NXT_deadReakoning_walk_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_deadReakoning_walk &);

        static WBFunctorBase *bind(WEBOTS_NXT_deadReakoning_walk_WBFunctor_T *obj, void (WEBOTS_NXT_deadReakoning_walk_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_deadReakoning_walk &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_deadReakoning_walk_WBFunctor<WEBOTS_NXT_deadReakoning_walk_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_deadReakoning_walk_DEFINED


#ifdef WEBOTS_NXT_colorLine_walk_DEFINED
template <typename WEBOTS_NXT_colorLine_walk_WBFunctor_T >
class WEBOTS_NXT_colorLine_walk_WBFunctor: public WBFunctor<WEBOTS_NXT_colorLine_walk_WBFunctor_T > 
{
public:
        WEBOTS_NXT_colorLine_walk_WBFunctor(WEBOTS_NXT_colorLine_walk_WBFunctor_T* obj, void (WEBOTS_NXT_colorLine_walk_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_colorLine_walk &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_colorLine_walk_WBFunctor_T >(obj, (void (WEBOTS_NXT_colorLine_walk_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_colorLine_walk result = guWhiteboard::WEBOTS_NXT_colorLine_walk_t().get_from(m);
                WEBOTS_NXT_colorLine_walk_function_t funct((void (WEBOTS_NXT_colorLine_walk_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_colorLine_walk &))WBFunctor<WEBOTS_NXT_colorLine_walk_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_colorLine_walk_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_colorLine_walk_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_colorLine_walk_WBFunctor_T::*WEBOTS_NXT_colorLine_walk_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_colorLine_walk &);

        static WBFunctorBase *bind(WEBOTS_NXT_colorLine_walk_WBFunctor_T *obj, void (WEBOTS_NXT_colorLine_walk_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_colorLine_walk &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_colorLine_walk_WBFunctor<WEBOTS_NXT_colorLine_walk_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_colorLine_walk_DEFINED


#ifdef WEBOTS_NXT_gridMotions_DEFINED
template <typename WEBOTS_NXT_gridMotions_WBFunctor_T >
class WEBOTS_NXT_gridMotions_WBFunctor: public WBFunctor<WEBOTS_NXT_gridMotions_WBFunctor_T > 
{
public:
        WEBOTS_NXT_gridMotions_WBFunctor(WEBOTS_NXT_gridMotions_WBFunctor_T* obj, void (WEBOTS_NXT_gridMotions_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_gridMotions &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_gridMotions_WBFunctor_T >(obj, (void (WEBOTS_NXT_gridMotions_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_gridMotions result = guWhiteboard::WEBOTS_NXT_gridMotions_t().get_from(m);
                WEBOTS_NXT_gridMotions_function_t funct((void (WEBOTS_NXT_gridMotions_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_gridMotions &))WBFunctor<WEBOTS_NXT_gridMotions_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_gridMotions_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_gridMotions_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_gridMotions_WBFunctor_T::*WEBOTS_NXT_gridMotions_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_gridMotions &);

        static WBFunctorBase *bind(WEBOTS_NXT_gridMotions_WBFunctor_T *obj, void (WEBOTS_NXT_gridMotions_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_gridMotions &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_gridMotions_WBFunctor<WEBOTS_NXT_gridMotions_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_gridMotions_DEFINED


#ifdef VisionBall_DEFINED
template <typename VisionBall_WBFunctor_T >
class VisionBall_WBFunctor: public WBFunctor<VisionBall_WBFunctor_T > 
{
public:
        VisionBall_WBFunctor(VisionBall_WBFunctor_T* obj, void (VisionBall_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::VisionBall &), guWhiteboard::WBTypes t): WBFunctor<VisionBall_WBFunctor_T >(obj, (void (VisionBall_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::VisionBall result = guWhiteboard::VisionBall_t().get_from(m);
                VisionBall_function_t funct((void (VisionBall_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::VisionBall &))WBFunctor<VisionBall_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<VisionBall_WBFunctor_T >::fObject->*funct)(WBFunctor<VisionBall_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (VisionBall_WBFunctor_T::*VisionBall_function_t) (guWhiteboard::WBTypes, guWhiteboard::VisionBall &);

        static WBFunctorBase *bind(VisionBall_WBFunctor_T *obj, void (VisionBall_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::VisionBall &), guWhiteboard::WBTypes t) { return new VisionBall_WBFunctor<VisionBall_WBFunctor_T >(obj, f, t); }
};

#endif //VisionBall_DEFINED


#ifdef VisionGoals_DEFINED
template <typename VisionGoals_WBFunctor_T >
class VisionGoals_WBFunctor: public WBFunctor<VisionGoals_WBFunctor_T > 
{
public:
        VisionGoals_WBFunctor(VisionGoals_WBFunctor_T* obj, void (VisionGoals_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::VisionGoals &), guWhiteboard::WBTypes t): WBFunctor<VisionGoals_WBFunctor_T >(obj, (void (VisionGoals_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::VisionGoals result = guWhiteboard::VisionGoals_t().get_from(m);
                VisionGoals_function_t funct((void (VisionGoals_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::VisionGoals &))WBFunctor<VisionGoals_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<VisionGoals_WBFunctor_T >::fObject->*funct)(WBFunctor<VisionGoals_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (VisionGoals_WBFunctor_T::*VisionGoals_function_t) (guWhiteboard::WBTypes, guWhiteboard::VisionGoals &);

        static WBFunctorBase *bind(VisionGoals_WBFunctor_T *obj, void (VisionGoals_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::VisionGoals &), guWhiteboard::WBTypes t) { return new VisionGoals_WBFunctor<VisionGoals_WBFunctor_T >(obj, f, t); }
};

#endif //VisionGoals_DEFINED


#ifdef WalkData_DEFINED
template <typename WalkData_WBFunctor_T >
class WalkData_WBFunctor: public WBFunctor<WalkData_WBFunctor_T > 
{
public:
        WalkData_WBFunctor(WalkData_WBFunctor_T* obj, void (WalkData_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WalkData &), guWhiteboard::WBTypes t): WBFunctor<WalkData_WBFunctor_T >(obj, (void (WalkData_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WalkData result = guWhiteboard::WalkData_t().get_from(m);
                WalkData_function_t funct((void (WalkData_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WalkData &))WBFunctor<WalkData_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WalkData_WBFunctor_T >::fObject->*funct)(WBFunctor<WalkData_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WalkData_WBFunctor_T::*WalkData_function_t) (guWhiteboard::WBTypes, guWhiteboard::WalkData &);

        static WBFunctorBase *bind(WalkData_WBFunctor_T *obj, void (WalkData_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WalkData &), guWhiteboard::WBTypes t) { return new WalkData_WBFunctor<WalkData_WBFunctor_T >(obj, f, t); }
};

#endif //WalkData_DEFINED


#ifdef TeleoperationControlStatus_DEFINED
template <typename TeleoperationControlStatus_WBFunctor_T >
class TeleoperationControlStatus_WBFunctor: public WBFunctor<TeleoperationControlStatus_WBFunctor_T > 
{
public:
        TeleoperationControlStatus_WBFunctor(TeleoperationControlStatus_WBFunctor_T* obj, void (TeleoperationControlStatus_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::TeleoperationControlStatus &), guWhiteboard::WBTypes t): WBFunctor<TeleoperationControlStatus_WBFunctor_T >(obj, (void (TeleoperationControlStatus_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::TeleoperationControlStatus result = guWhiteboard::TeleoperationControlStatus_t().get_from(m);
                TeleoperationControlStatus_function_t funct((void (TeleoperationControlStatus_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::TeleoperationControlStatus &))WBFunctor<TeleoperationControlStatus_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<TeleoperationControlStatus_WBFunctor_T >::fObject->*funct)(WBFunctor<TeleoperationControlStatus_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (TeleoperationControlStatus_WBFunctor_T::*TeleoperationControlStatus_function_t) (guWhiteboard::WBTypes, guWhiteboard::TeleoperationControlStatus &);

        static WBFunctorBase *bind(TeleoperationControlStatus_WBFunctor_T *obj, void (TeleoperationControlStatus_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::TeleoperationControlStatus &), guWhiteboard::WBTypes t) { return new TeleoperationControlStatus_WBFunctor<TeleoperationControlStatus_WBFunctor_T >(obj, f, t); }
};

#endif //TeleoperationControlStatus_DEFINED


template <typename TeleoperationConnection_WBFunctor_T >
class TeleoperationConnection_WBFunctor: public WBFunctor<TeleoperationConnection_WBFunctor_T > 
{
public:
        TeleoperationConnection_WBFunctor(TeleoperationConnection_WBFunctor_T* obj, void (TeleoperationConnection_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t): WBFunctor<TeleoperationConnection_WBFunctor_T >(obj, (void (TeleoperationConnection_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                int result = guWhiteboard::TeleoperationConnection_t().get_from(m);
                TeleoperationConnection_function_t funct((void (TeleoperationConnection_WBFunctor_T::*)(guWhiteboard::WBTypes, int &))WBFunctor<TeleoperationConnection_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<TeleoperationConnection_WBFunctor_T >::fObject->*funct)(WBFunctor<TeleoperationConnection_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (TeleoperationConnection_WBFunctor_T::*TeleoperationConnection_function_t) (guWhiteboard::WBTypes, int &);

        static WBFunctorBase *bind(TeleoperationConnection_WBFunctor_T *obj, void (TeleoperationConnection_WBFunctor_T::*f)(guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t) { return new TeleoperationConnection_WBFunctor<TeleoperationConnection_WBFunctor_T >(obj, f, t); }
};



template <typename UDPWBNumber_WBFunctor_T >
class UDPWBNumber_WBFunctor: public WBFunctor<UDPWBNumber_WBFunctor_T > 
{
public:
        UDPWBNumber_WBFunctor(UDPWBNumber_WBFunctor_T* obj, void (UDPWBNumber_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t): WBFunctor<UDPWBNumber_WBFunctor_T >(obj, (void (UDPWBNumber_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                int result = guWhiteboard::UDPWBNumber_t().get_from(m);
                UDPWBNumber_function_t funct((void (UDPWBNumber_WBFunctor_T::*)(guWhiteboard::WBTypes, int &))WBFunctor<UDPWBNumber_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<UDPWBNumber_WBFunctor_T >::fObject->*funct)(WBFunctor<UDPWBNumber_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (UDPWBNumber_WBFunctor_T::*UDPWBNumber_function_t) (guWhiteboard::WBTypes, int &);

        static WBFunctorBase *bind(UDPWBNumber_WBFunctor_T *obj, void (UDPWBNumber_WBFunctor_T::*f)(guWhiteboard::WBTypes, int &), guWhiteboard::WBTypes t) { return new UDPWBNumber_WBFunctor<UDPWBNumber_WBFunctor_T >(obj, f, t); }
};



#ifdef WEBOTS_NXT_bumper_DEFINED
template <typename WEBOTS_NXT_bumper_WBFunctor_T >
class WEBOTS_NXT_bumper_WBFunctor: public WBFunctor<WEBOTS_NXT_bumper_WBFunctor_T > 
{
public:
        WEBOTS_NXT_bumper_WBFunctor(WEBOTS_NXT_bumper_WBFunctor_T* obj, void (WEBOTS_NXT_bumper_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bumper &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_bumper_WBFunctor_T >(obj, (void (WEBOTS_NXT_bumper_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_bumper result = guWhiteboard::WEBOTS_NXT_bumper_t().get_from(m);
                WEBOTS_NXT_bumper_function_t funct((void (WEBOTS_NXT_bumper_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bumper &))WBFunctor<WEBOTS_NXT_bumper_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_bumper_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_bumper_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_bumper_WBFunctor_T::*WEBOTS_NXT_bumper_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bumper &);

        static WBFunctorBase *bind(WEBOTS_NXT_bumper_WBFunctor_T *obj, void (WEBOTS_NXT_bumper_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_bumper &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_bumper_WBFunctor<WEBOTS_NXT_bumper_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_bumper_DEFINED


#ifdef WEBOTS_NXT_vector_bridge_DEFINED
template <typename WEBOTS_NXT_vector_bridge_WBFunctor_T >
class WEBOTS_NXT_vector_bridge_WBFunctor: public WBFunctor<WEBOTS_NXT_vector_bridge_WBFunctor_T > 
{
public:
        WEBOTS_NXT_vector_bridge_WBFunctor(WEBOTS_NXT_vector_bridge_WBFunctor_T* obj, void (WEBOTS_NXT_vector_bridge_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_vector_bridge &), guWhiteboard::WBTypes t): WBFunctor<WEBOTS_NXT_vector_bridge_WBFunctor_T >(obj, (void (WEBOTS_NXT_vector_bridge_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::WEBOTS_NXT_vector_bridge result = guWhiteboard::WEBOTS_NXT_vector_bridge_t().get_from(m);
                WEBOTS_NXT_vector_bridge_function_t funct((void (WEBOTS_NXT_vector_bridge_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_vector_bridge &))WBFunctor<WEBOTS_NXT_vector_bridge_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<WEBOTS_NXT_vector_bridge_WBFunctor_T >::fObject->*funct)(WBFunctor<WEBOTS_NXT_vector_bridge_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (WEBOTS_NXT_vector_bridge_WBFunctor_T::*WEBOTS_NXT_vector_bridge_function_t) (guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_vector_bridge &);

        static WBFunctorBase *bind(WEBOTS_NXT_vector_bridge_WBFunctor_T *obj, void (WEBOTS_NXT_vector_bridge_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::WEBOTS_NXT_vector_bridge &), guWhiteboard::WBTypes t) { return new WEBOTS_NXT_vector_bridge_WBFunctor<WEBOTS_NXT_vector_bridge_WBFunctor_T >(obj, f, t); }
};

#endif //WEBOTS_NXT_vector_bridge_DEFINED


#ifdef VisionLines_DEFINED
template <typename VisionLines_WBFunctor_T >
class VisionLines_WBFunctor: public WBFunctor<VisionLines_WBFunctor_T > 
{
public:
        VisionLines_WBFunctor(VisionLines_WBFunctor_T* obj, void (VisionLines_WBFunctor_T::*pFunc) (guWhiteboard::WBTypes, guWhiteboard::VisionLines &), guWhiteboard::WBTypes t): WBFunctor<VisionLines_WBFunctor_T >(obj, (void (VisionLines_WBFunctor_T::*) (guWhiteboard::WBTypes, gu_simple_message*))pFunc, t) { }

        void call(gu_simple_message *m)
        {
                guWhiteboard::VisionLines result = guWhiteboard::VisionLines_t().get_from(m);
                VisionLines_function_t funct((void (VisionLines_WBFunctor_T::*)(guWhiteboard::WBTypes, guWhiteboard::VisionLines &))WBFunctor<VisionLines_WBFunctor_T >::get_s_func_ptr());
                (WBFunctor<VisionLines_WBFunctor_T >::fObject->*funct)(WBFunctor<VisionLines_WBFunctor_T >::type_enum, result);
        }
        
        typedef void (VisionLines_WBFunctor_T::*VisionLines_function_t) (guWhiteboard::WBTypes, guWhiteboard::VisionLines &);

        static WBFunctorBase *bind(VisionLines_WBFunctor_T *obj, void (VisionLines_WBFunctor_T::*f)(guWhiteboard::WBTypes, guWhiteboard::VisionLines &), guWhiteboard::WBTypes t) { return new VisionLines_WBFunctor<VisionLines_WBFunctor_T >(obj, f, t); }
};

#endif //VisionLines_DEFINED


